# Generated by Django 4.2.30 on 2026-08-31 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=32, unique=True, verbose_name='资产编号')),
                ('sn', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='序列号')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='品牌')),
                ('model_spec', models.CharField(blank=True, max_length=100, verbose_name='型号规格')),
                ('status', models.CharField(choices=[('in_stock', '在库'), ('in_use', '在用'), ('repairing', '维修中'), ('idle', '闲置'), ('scrapped', '已报废')], default='in_stock', max_length=16, verbose_name='状态')),
                ('purchase_date', models.DateField(verbose_name='投产日期')),
                ('original_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='原值(元)')),
                ('useful_life', models.IntegerField(blank=True, help_text='留空继承类别默认', null=True, verbose_name='使用年限(年)')),
                ('salvage_rate', models.FloatField(blank=True, help_text='留空继承类别默认', null=True, verbose_name='残值率')),
                ('custom', models.JSONField(blank=True, default=dict, verbose_name='自定义字段')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='类别名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='类别编码')),
                ('default_life', models.IntegerField(default=8, verbose_name='默认报废年限(年)')),
                ('default_salvage_rate', models.FloatField(default=0.05, verbose_name='默认残值率')),
                ('field_schema', models.JSONField(blank=True, default=list, verbose_name='自定义字段定义')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='部门名称')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='部门编码')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RepairOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='报修日期')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='完成日期')),
                ('fault_desc', models.TextField(verbose_name='故障描述')),
                ('parts_replaced', models.JSONField(blank=True, default=list, verbose_name='更换配件明细')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='人工/服务费(元)')),
                ('vendor', models.CharField(blank=True, max_length=64, verbose_name='维修商')),
                ('status', models.CharField(choices=[('pending', '待维修'), ('done', '已完成'), ('scrapped', '维修后报废')], default='pending', max_length=12, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='assets.asset', verbose_name='资产')),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='位置名称')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.department', verbose_name='管理部门')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='assets.location', verbose_name='上级位置')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LifecycleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '入库'), ('assign', '领用'), ('return', '归还'), ('transfer', '调拨'), ('repair', '维修'), ('stocktake', '盘点'), ('scrap', '报废'), ('update', '信息变更')], max_length=16, verbose_name='动作')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle', to='assets.asset', verbose_name='资产')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.assetcategory', verbose_name='资产类别'),
        ),
        migrations.AddField(
            model_name='asset',
            name='custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='使用人'),
        ),
        migrations.AddField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.department', verbose_name='所属部门'),
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.location', verbose_name='存放位置'),
        ),
    ]
