# Generated by Django 4.2.30 on 2026-09-01 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocktake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('status', models.CharField(choices=[('ongoing', '进行中'), ('finished', '已完成')], default='ongoing', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.assetcategory', verbose_name='限定类别')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.department', verbose_name='限定部门')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_no', models.CharField(max_length=32, unique=True, verbose_name='流程单号')),
                ('flow_type', models.CharField(choices=[('assign', '领用'), ('return', '归还'), ('transfer', '调拨'), ('scrap', '报废')], max_length=12, verbose_name='类型')),
                ('reason', models.TextField(verbose_name='事由')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已驳回')], default='pending', max_length=10, verbose_name='状态')),
                ('approve_remark', models.CharField(blank=True, max_length=200, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows_applied', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flows_approved', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='assets.asset', verbose_name='资产')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.department', verbose_name='目标部门')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.location', verbose_name='目标位置')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flows_to', to=settings.AUTH_USER_MODEL, verbose_name='目标使用人')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StocktakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found', models.BooleanField(default=False, verbose_name='已确认')),
                ('found_at', models.DateTimeField(blank=True, null=True)),
                ('found_location', models.CharField(blank=True, max_length=100, verbose_name='实盘位置')),
                ('unexpected', models.BooleanField(default=False, verbose_name='账外')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset', verbose_name='资产')),
                ('stocktake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assets.stocktake', verbose_name='任务')),
            ],
            options={
                'unique_together': {('stocktake', 'asset')},
            },
        ),
    ]
