# Generated by Django 4.2.30 on 2026-09-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_stocktake_assetflow_stocktakeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktake',
            name='custom_filter',
            field=models.JSONField(blank=True, help_text='如 {"terminal_type": "生产类终端"}', null=True, verbose_name='自定义标签过滤'),
        ),
    ]
