# Generated by Django 4.2.30 on 2026-09-01 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_stocktake_custom_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='部门名称')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='层级')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='assets.deptnode', verbose_name='上级')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('parent', 'name')},
            },
        ),
    ]
