# Generated by Django 4.2.30 on 2026-09-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_deptnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='deptnode',
            name='src_names',
            field=models.JSONField(blank=True, default=list, help_text='挂在该节点下的 Department 全名列表', verbose_name='原始部门全名'),
        ),
    ]
